### ISSUE TITLE
JH71x0 needs documented 

### ISSUE THREAD

**Issue by robertlipe** [starfive-tech/sft-riscv-opensbi#3]
So it's not forgotten, JH7100 and JH7110 need documented in
https://github.com/starfive-tech/sft-riscv-opensbi/blob/starfive/docs/platform/platform.md
and probably a dedicated doc in
https://github.com/starfive-tech/sft-riscv-opensbi/tree/starfive/docs/platform

**Comment by pdp7** [comment]
@robertlipe could you please open this in  https://github.com/starfive-tech/opensbi ?

I just updated the README to redirect people to that repo
